stages:
  - test
  - name: pypi
    if: branch = master

language: python
services: mongodb

cache: pip

python:
  - "3.6"

install:
  - pip install -r requirements.txt -e .
  - pip install pytest-cov codecov


jobs:
  include:
    - script: pytest -v --cov=./gcmcworkflow
      after_success: codecov
    - stage: pypi
      install: skip
      script: echo hello
      deploy:
        provider: pypi
	user: "richardjgowers"
	password:
	  secure: "derp"
	on:
	  tags: true