stages:
  - test
  - deploy

language: python
services: mongodb

cache: pip

python:
  - "3.6"

install:
  - pip install -r requirements.txt -e .
  - pip install pytest-cov codecov


jobs:
  include:
    - script: pytest -v --cov=./gcmcworkflow
      after_success: codecov
    - stage: deploy
      on:
        - branch: master
        - tags: true
      install: skip
      script: echo hello