{% set data = load_setup_py_data() %}

package:
  name: gcmcworkflow
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - fireworks
    - pyyaml
    - docopt
    - pandas
    - pandas >=0.20.0
    - dill
    - scipy
    - statsmodels
    - hydraspa >=0.3.0
    - terminaltables
    - termcolor
    - mmtf-python
    - scikit-learn
    - MDAnalysis >=0.17.0

test:
  imports:
    - gcmcworkflow
  commands:
    - gcmcworkflow -h